name: cicd

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]


jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: dart format --set-exit-if-changed .


  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - uses: invertase/github-action-dart-analyzer@v3
        with:
          fatal-infos: true